#!/bin/bash
# Author: @FershoUno
# Translation code made by crims0n from the MiniOS installer project


check_root(){
    if [[ $EUID -ne 0 ]]; then
        pkexec "$0"
        exit 0
    fi
}

translate() {
    local TEXT=$1
    if [ ! -f /etc/plurios-release ]; then
        local LNG=$(locale | grep LANG | cut -d= -f2 | cut -d_ -f1)
    else
        if grep -q Pro plurios-release ; then
        LNG=es
        elif grep -q Aymara plurios-release ; then
        LNG=ay
        fi
    fi
    local TRANSLATION_FILE="translate/$LNG.json"
    if [ -f "$TRANSLATION_FILE" ]; then
        local TRANSLATION=$(jq -r --arg TEXT "$TEXT" '.[$TEXT]' "$TRANSLATION_FILE")
        if [ "$TRANSLATION" != "null" ]; then
            echo $TRANSLATION
        else
            echo $TEXT
        fi
    else
        echo $TEXT
    fi
}

detect_the_swap_type() {
    local NAME
    while read -r NAME _; do
        case "$NAME" in
            /dev/zram*)
                    MESSAGE_SWAP=$(echo "$(translate 'ZRAM detected:') $NAME")
                    MESSAGE_TEXT=$(echo "$(translate 'It is not possible to manage this type of swap.')")
                return
                ;;
            /dev/*)
                    MESSAGE_SWAP=$(echo "$(translate 'Swap partition detected:') $NAME")
                    MESSAGE_TEXT=$(echo "$(translate 'It is not possible to manage this type of swap.')")
                return
                ;;
            *)
                if [[ -f "$NAME" ]]; then
                    MESSAGE_SWAP=$(echo "$(translate 'Swapfile detected:') $NAME")
                    MESSAGE_TEXT=$(echo "$(translate 'It is possible to manage this type of swap.')")
                    return
                fi
                ;;
        esac
    done < <(swapon --noheadings --show=NAME)
    MESSAGE_TEXT=$(echo "$(translate 'No active swap found.')")
}

alert_noswap(){
    detect_the_swap_type
yad --window-icon "ubiquity" \
    --borders=15 \
    --width=300 \
    --height=100 \
    --image "dialog-question" \
	--title "$(translate 'Alert')" \
	--text "$MESSAGE_SWAP\n$MESSAGE_TEXT" \
	--button="$(translate 'Add')!gtk-add":0 \
	--button="$(translate 'Cancel')!gtk-cancel":1 \
	option=$?

[[ $option -eq 0 ]] && echo "$(translate 'Creating SWAPFILE')"
[[ $option -eq 1 ]] && echo "$(translate 'Exit')"
}

check_root
alert_noswap